export const categories = [
    {
        id: 1,
        name: 'Pizza',
        image: require('../assets/images/pizzaIcon.png'),
    },
    {
        id: 2,
        name: 'Burger',
        image: require('../assets/images/pizzaIcon.png'),
    },
    {
        id: 3,
        name: 'Italian',
        image: require('../assets/images/pizzaIcon.png'),
    },
    {
        id: 4,
        name: 'Chinese',
        image: require('../assets/images/pizzaIcon.png'),
    },
    {
        id: 5,
        name: 'Noodles',
        image: require('../assets/images/pizzaIcon.png'),
    },
    {
        id: 6,
        name: 'Sweets',
        image: require('../assets/images/pizzaIcon.png'),
    },
];

export const featured = {
    id: 1,
    title: 'Hot and Spicy',
    description: 'Soft and tender fried chicken',
    restaurants: [
        {
            id: 1,
            name: 'Papa Johns',
            image: require('../assets/images/pizza.png'),
            description: 'Hot and spicy pizzas',
            lng: 38.2145602,
            lat: -85.5324269,
            address: '434 second street',
            stars: 4,
            reviews: '4.4k',
            category: 'Fast Food',
            dishes: [
                {
                    id: 1,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/pizzaDish.png'),
                },
                {
                    id: 2,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/pizzaDish.png'),
                },
                {
                    id: 3,
                    name: 'Pizza',
                    description: 'Cheezy garlic pizza',
                    price: 10,
                    image: require('../assets/images/pizzaDish.png'),
                },
            ],
        },
        {
            id: 2,
            name: 'Burger King',
            image: require('../assets/images/pizza.png'),
            description: 'Delicious burgers',
            lng: 40.712776,
            lat: -74.005974,
            address: '123 Main St',
            stars: 4.5,
            reviews: '3.2k',
            category: 'Fast Food',
            dishes: [
                {
                    id: 1,
                    name: 'Whopper',
                    description: 'Juicy beef burger',
                    price: 8,
                    image: require('../assets/images/pizzaDish.png'),
                },
                {
                    id: 2,
                    name: 'Fries',
                    description: 'Crispy french fries',
                    price: 3,
                    image: require('../assets/images/pizzaDish.png'),
                },
            ],
        },
        {
            id: 3,
            name: 'Taco Bell',
            image: require('../assets/images/pizza.png'),
            description: 'Mexican inspired food',
            lng: 34.052235,
            lat: -118.243683,
            address: '456 Elm St',
            stars: 4.2,
            reviews: '2.8k',
            category: 'Fast Food',
            dishes: [
                {
                    id: 1,
                    name: 'Taco',
                    description: 'Spicy beef taco',
                    price: 5,
                    image: require('../assets/images/pizzaDish.png'),
                },
                {
                    id: 2,
                    name: 'Burrito',
                    description: 'Chicken burrito',
                    price: 7,
                    image: require('../assets/images/pizzaDish.png'),
                },
            ],
        },
        {
            id: 4,
            name: 'KFC',
            image: require('../assets/images/pizza.png'),
            description: 'Fried chicken',
            lng: 51.507351,
            lat: -0.127758,
            address: '789 Oak St',
            stars: 4.3,
            reviews: '3.5k',
            category: 'Fast Food',
            dishes: [
                {
                    id: 1,
                    name: 'Fried Chicken',
                    description: 'Crispy fried chicken',
                    price: 12,
                    image: require('../assets/images/pizzaDish.png'),
                },
                {
                    id: 2,
                    name: 'Mashed Potatoes',
                    description: 'Creamy mashed potatoes',
                    price: 4,
                    image: require('../assets/images/pizzaDish.png'),
                },
            ],
        },
        {
            id: 5,
            name: 'Subway',
            image: require('../assets/images/pizza.png'),
            description: 'Fresh sandwiches',
            lng: 48.856613,
            lat: 2.352222,
            address: '101 Pine St',
            stars: 4.1,
            reviews: '2.9k',
            category: 'Fast Food',
            dishes: [
                {
                    id: 1,
                    name: 'Sub Sandwich',
                    description: 'Turkey sub sandwich',
                    price: 9,
                    image: require('../assets/images/pizzaDish.png'),
                },
                {
                    id: 2,
                    name: 'Salad',
                    description: 'Fresh garden salad',
                    price: 6,
                    image: require('../assets/images/pizzaDish.png'),
                },
            ],
        },
        {
            id: 6,
            name: 'Dominos',
            image: require('../assets/images/pizza.png'),
            description: 'Delicious pizzas',
            lng: 41.878113,
            lat: -87.629799,
            address: '202 Maple St',
            stars: 4.4,
            reviews: '3.7k',
            category: 'Fast Food',
            dishes: [
                {
                    id: 1,
                    name: 'Pepperoni Pizza',
                    description: 'Pepperoni pizza with extra cheese',
                    price: 11,
                    image: require('../assets/images/pizzaDish.png'),
                },
                {
                    id: 2,
                    name: 'Garlic Bread',
                    description: 'Garlic breadsticks',
                    price: 5,
                    image: require('../assets/images/pizzaDish.png'),
                },
            ],
        },
        {
            id: 7,
            name: 'Chipotle',
            image: require('../assets/images/pizza.png'),
            description: 'Mexican grill',
            lng: 34.052235,
            lat: -118.243683,
            address: '303 Cedar St',
            stars: 4.6,
            reviews: '4.1k',
            category: 'Fast Food',
            dishes: [
                {
                    id: 1,
                    name: 'Burrito Bowl',
                    description: 'Chicken burrito bowl',
                    price: 10,
                    image: require('../assets/images/pizzaDish.png'),
                },
                {
                    id: 2,
                    name: 'Chips and Guac',
                    description: 'Chips with guacamole',
                    price: 4,
                    image: require('../assets/images/pizzaDish.png'),
                },
            ],
        },
        {
            id: 8,
            name: 'Wendys',
            image: require('../assets/images/pizza.png'),
            description: 'Fresh, never frozen burgers',
            lng: 40.712776,
            lat: -74.005974,
            address: '404 Birch St',
            stars: 4.2,
            reviews: '3.0k',
            category: 'Fast Food',
            dishes: [
                {
                    id: 1,
                    name: 'Baconator',
                    description: 'Bacon cheeseburger',
                    price: 9,
                    image: require('../assets/images/pizzaDish.png'),
                },
                {
                    id: 2,
                    name: 'Frosty',
                    description: 'Chocolate frosty',
                    price: 3,
                    image: require('../assets/images/pizzaDish.png'),
                },
            ],
        },
        {
            id: 9,
            name: 'Five Guys',
            image: require('../assets/images/pizza.png'),
            description: 'Handcrafted burgers and fries',
            lng: 51.507351,
            lat: -0.127758,
            address: '505 Spruce St',
            stars: 4.5,
            reviews: '3.8k',
            category: 'Fast Food',
            dishes: [
                {
                    id: 1,
                    name: 'Cheeseburger',
                    description: 'Double cheeseburger',
                    price: 11,
                    image: require('../assets/images/pizzaDish.png'),
                },
                {
                    id: 2,
                    name: 'Cajun Fries',
                    description: 'Spicy cajun fries',
                    price: 4,
                    image: require('../assets/images/pizzaDish.png'),
                },
            ],
        },
        {
            id: 10,
            name: 'Panda Express',
            image: require('../assets/images/pizza.png'),
            description: 'American Chinese cuisine',
            lng: 48.856613,
            lat: 2.352222,
            address: '606 Willow St',
            stars: 4.3,
            reviews: '3.4k',
            category: 'Fast Food',
            dishes: [
                {
                    id: 1,
                    name: 'Orange Chicken',
                    description: 'Sweet and tangy chicken',
                    price: 9,
                    image: require('../assets/images/pizzaDish.png'),
                },
                {
                    id: 2,
                    name: 'Chow Mein',
                    description: 'Stir-fried noodles',
                    price: 7,
                    image: require('../assets/images/pizzaDish.png'),
                },
            ],
        },
        {
            id: 11,
            name: 'Shake Shack',
            image: require('../assets/images/pizza.png'),
            description: 'Burgers, fries, and shakes',
            lng: 41.878113,
            lat: -87.629799,
            address: '707 Ash St',
            stars: 4.6,
            reviews: '4.2k',
            category: 'Fast Food',
            dishes: [
                {
                    id: 1,
                    name: 'ShackBurger',
                    description: 'Cheeseburger with lettuce, tomato, and ShackSauce',
                    price: 8,
                    image: require('../assets/images/pizzaDish.png'),
                },
                {
                    id: 2,
                    name: 'Crinkle-Cut Fries',
                    description: 'Crispy crinkle-cut fries',
                    price: 3,
                    image: require('../assets/images/pizzaDish.png'),
                },
            ],
        },
        {
            id: 12,
            name: 'In-N-Out Burger',
            image: require('../assets/images/pizza.png'),
            description: 'Fresh burgers and fries',
            lng: 34.052235,
            lat: -118.243683,
            address: '808 Pine St',
            stars: 4.7,
            reviews: '4.5k',
            category: 'Fast Food',
            dishes: [
                {
                    id: 1,
                    name: 'Double-Double',
                    description: 'Double cheeseburger',
                    price: 7,
                    image: require('../assets/images/pizzaDish.png'),
                },
                {
                    id: 2,
                    name: 'Animal Style Fries',
                    description: 'Fries with cheese, grilled onions, and spread',
                    price: 4,
                    image: require('../assets/images/pizzaDish.png'),
                },
            ],
        },
    ],
};

export type Featured = typeof featured;
export type Restaurant = typeof featured.restaurants[0];